IO.puts("")
IO.puts("=============== TREE ADD & LOOKUP =================")
IO.puts("")

tree = EnvTree.add(nil, :d, 42)
tree = EnvTree.add(tree, :d, 1337)
tree = EnvTree.add(tree, :b, 10)
tree = EnvTree.add(tree, :a, 8)
tree = EnvTree.add(tree, :n, 100)
tree = EnvTree.add(tree, :m, 89)

IO.inspect(tree)
IO.puts("")

IO.inspect(EnvTree.lookup(tree, :d))
IO.inspect(EnvTree.lookup(tree, :b))
IO.inspect(EnvTree.lookup(tree, :a))
IO.inspect(EnvTree.lookup(tree, :m))
IO.inspect(EnvTree.lookup(tree, :o))
IO.inspect(EnvTree.lookup(tree, :n))

IO.puts("")
IO.puts("=============== TREE ADD & REMOVE #1 =================")
IO.puts("")

tree = nil
tree = EnvTree.add(tree, :c, "c")
tree = EnvTree.add(tree, :b, "b")
tree = EnvTree.add(tree, :a, "a")
tree = EnvTree.add(tree, :d, "d")
tree = EnvTree.add(tree, :e, "e")

IO.inspect(tree)
IO.puts("")
IO.inspect(EnvTree.remove(tree, :a))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :b))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :c))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :d))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :e))

IO.puts("")
IO.puts("=============== TREE ADD & REMOVE #2 =================")
IO.puts("")

tree = nil
tree = EnvTree.add(tree, :m, "m")
tree = EnvTree.add(tree, :b, "b")
tree = EnvTree.add(tree, :n, "n")
tree = EnvTree.add(tree, :a, "a")
tree = EnvTree.add(tree, :c, "c")
tree = EnvTree.add(tree, :o, "o")

IO.inspect(tree)
IO.puts("")
IO.inspect(EnvTree.remove(tree, :m))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :b))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :n))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :a))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :c))
IO.puts("")
IO.inspect(EnvTree.remove(tree, :o))
